lnguage: python

python:
        - 3.6

notifications:
        email: false

        services:
                - mysql

        before_install:
                - mysql -e 'CREATE DATABASE IF NOT EXISTS users_test;'

        install:
                - pip install -r ./requirements.txt

        script: 
                - python manage.py test
